### ISSUE TITLE
Bug: Uploading json files with relative paths

### ISSUE THREAD

**Issue by MDavidson17** [linz/geostore#890] opened 2021-07-14 02:30 UTC
## Bug Description

As a topo developer I want to be able to upload STAC metadata with relative href paths, for example:
`"href" : "./collection.json"`
or 
`"href": "../collection.json"`

## How to Reproduce

1. Create STAC metadata with relative paths
1. Run geostore upload process

What did you expect to happen? 
No error
What actually happened? 
```json
{
    "status_code": 200,
    "body": {
        "step_function": {
            "status": "Running"
        },
        "validation": {
            "status": "Failed",
            "errors": [
                {
                    "check": "staging bucket access",
                    "result": "Failed",
                    "url": "s3://linz-historical-imagery-staging/GeostoreTestData/SURVEY_1/./collection.json",
                    "details": {
                        "message": "An error occurred (NoSuchKey) when calling the GetObject operation: The specified key does not exist."
                    }
                }
            ]
        },
        "metadata_upload": {
            "status": "Skipped",
            "errors": []
        },
        "asset_upload": {
            "status": "Skipped",
            "errors": []
        }
    }
}
```

```json
{
    "StatusCode": 200,
    "ExecutedVersion": "$LATEST"
}
```
## Software Context

Operating system: 
Linux
Environment: 
nonprod
## Additional context
https://github.com/linz/topo-processor

**Comment by billgeo** [comment] 2021-07-18 21:34
@l0b0 has this one also been fixed and confirmed by Topo team? If so, feel free to close it. I'm happy if they are happy.

**Comment by l0b0** [comment] 2021-07-19 00:58
Turns out there is still a bug in the post-processing. I believe I dealt with one bug (or possibly a red herring), but it's not done, unfortunately.

**Comment by l0b0** [comment] 2021-07-28 03:38
Fixed in https://github.com/linz/geostore/pull/910 and https://github.com/linz/geostore/pull/895. Added a test for the metadata produced by pystac in https://github.com/linz/geostore/pull/924.

**Comment by billgeo** [comment] 2021-07-29 03:38
@MDavidson17 are you able to retest and confirm this is fixed? @l0b0 is on leave for a couple of weeks, but @MitchellPaff can help if you want someone to help?

**Comment by billgeo** [comment] 2021-07-29 03:39
Feel free to close it when you're happy.

**Closed** 2021-07-30 04:41 UTC
Labels: bug
