### ISSUE TITLE
Add deployment version to log messages

### ISSUE THREAD

**Issue by l0b0** [linz/geostore#225] opened 2021-02-04 21:15 UTC
To be able to distinguish errors in one version from errors in another version we should inject a deployment version — probably the Git commit ID, for simplicity and guaranteed uniqueness — into each log message.

##Tasks##
-[ ] Define log message layout (refer to LINZ Standard)
-[ ] replace existing log messages

**Comment by billgeo** [comment] 2021-11-22 01:42
Closing duplicate of #1195

**Closed** 2021-11-22 01:42 UTC
